- .gitignore
- src/index.js
- test/index.spec.js
After working on an example I ran into some inconsistency issues with peer ids not being proper ids.
This PR ensures that the PeerInfo returned from findProviders contains an actual PeerID.
> fix: better support peer ids

- src/index.js
- test/index.spec.js
The PR aims to mitigate an issue where connections to the delegate node would stay open for an extended period. This change will pass the `timeout` param to the API allowing for better limiting.
* Adds the timeout param to `findProviders `, which is compatible with the kad dht. This also sets a default limit of 30 seconds to limit the http calls to the delegate. 
Reference: https://github.com/ipfs/go-ipfs/pull/4595#issuecomment-420927609
I have verified this using the [WIP libp2p implementation](https://github.com/libp2p/js-libp2p/pull/242) and a local go-ipfs delegate node.
> feat: add timeout defaults

- package.json
- src/index.js
- test/index.spec.js
Needed for next js-ipfs release. Had to port some changes from https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/7
Depends on:
cc @achingbrain
> chore: update deps

- .aegir.js
- package.json
- src/index.js
- test/index.spec.js
Still got a couple of tests failing and some weirdness around the upgrade from `ipfs-api` to `ipfs-http-client`.
~~Depends on ipfs/js-ipfsd-ctl#353~~
> feat: refactor to use async/await

- .gitignore
- package.json
- src/index.js
- test/index.spec.js
All HTTP requests made by this module are sent to the same delegate
host. Browsers throttle the number of concurrent requests per hostname.
Right now the limit is 6 per host, which suffocates connection pool to the delegate (https://github.com/libp2p/js-libp2p-delegated-content-routing/issues/12)
blocking it from being used for [preload in js-ipfs](https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/preload-browser.js) or [delegated peer routing](https://github.com/libp2p/js-libp2p-delegated-peer-routing).
This PR:
- introduces a task queue that limits the number of concurrent requests, making it safe to run in browser context
- adds debug logs
- changes default delegate
Additional optimizations:
- preload calls via `refs` are known to take time,
that is why we use separate queue …
> fix: limit concurrent HTTP requests

- package.json
- src/index.js
- test/index.spec.js
This is a backport of the fix from https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/16 that works with 0.2.x.
The goal is to include the fix in latest js-ipfs release (without waiting for async/await changes to be propagated to js-libp2p)
cc @alanshaw @jacobheun
> fix: limit concurrent HTTP requests  (backport for 0.2.x)

- package.json
- src/index.js
- test/index.spec.js
This PR renames timeout option to be consistent with the `libp2p-kad-dht` implementation, in order to both be used in the `libp2p` routers.
Other than that, dependencies were updated
BREAKING CHANGE: maxTimeout option renamed to timeout
> chore: rename timeout option

- package.json
- src/index.js
In the new version of `ipfs-http-client` the refs is an async iterator instead of a promise.:
https://github.com/ipfs/js-ipfs-http-client/blob/master/src/refs/index.js#L12
> fix: async it refs

- package.json
- src/index.js
- test/index.spec.js
Use `it-all` dependency instead of `async-iterator-all`
> chore: use it-all

- README.md
- package.json
- src/index.js
In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR removes the `peer-info` from being returned in the API, in favour of returning `{ id, addrs }` in the same way as [ipfs](https://github.com/ipfs/js-ipfs/blob/447b44d1b64714f5ed0cafba166ad0a4dbbb587c/packages/ipfs/src/core/components/dht.js#L61) does.
BREAKING CHANGE: findProviders returns id and addrs properties instead of peer-info instance
Needs:
> chore: remove peer-info from api

- README.md
- package.json
BREAKING CHANGE: The ipfs-http-client must now be installed
as a peer dependency. It is no longer included as a dependency
of this module.
The reason the http-client should be a peerDependency and
not a dependency is that its API requires knowledge of the
http-client (we pass in the api endpoint details).
Supersedes https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/31
> chore: make ipfs-http-client a peer dependency

- .aegir.js
- package.json
- test/index.spec.js
BREAKING CHANGE:
- all useage of node Buffers has been replaced with Uint8Arrays
- all deps now use Uint8Arrays instead of node Buffers
> fix: replace node buffers with uint8arrays

- .travis.yml
- README.md
- package.json
- src/index.js
- test/index.spec.js
Instead of the http client being a dependency of this module, accept
a pre-configured http client instance at construction time.
This resolves the weird dependency loop and means we can remove this
module from the no-hoist config in ipfs.
BREAKING CHANGE:
- An instance of ipfs http client is now a required argument
> fix: accept http client instance

- package.json
- src/index.js
Fixes this sort of error:
```
npm ERR! Conflicting peer dependency: ipfs-http-client@46.1.2
npm ERR! node_modules/ipfs-http-client
npm ERR!   peer ipfs-http-client@"^46.0.0" from libp2p-delegated-content-routing@0.7.0
npm ERR!   node_modules/libp2p-delegated-content-routing
npm ERR!     libp2p-delegated-content-routing@"^0.7.0" from the root project
```
> chore: update ipfs-http-client peer dep

- .travis.yml
- package.json
- src/index.js
- test/index.spec.js
The http endpoint we send the CID to be provided only understands
dag-pb nodes.
Change the endpoints from a non-recursive `ipfs refs` call to a
`ipfs block stat` instead as it does not try to interperet the data.
N.b. only the passed CID will be provided, not any children but since
the original call was a non-recursive `ipfs refs` the behaviour should
be the same.
Also expands the explanation of how the provide happens and adds the
number of found providers to the logging output to make debugging things
a little easier.
> feat: allow providing non-dag-pb nodes

- README.md
Make this module consistent with https://github.com/libp2p/js-libp2p-delegated-peer-routing#example by having a real host that people can just use.
> chore: update delegate host to existing host

- package.json
We added ipfs-http-client as a peer dep to signal to the user
that they should add the modules they depend on as deps of their project.
Starting with npm7 all peer deps get installed automatically which
defeats the purpose of our use of peer deps, so let's remove them.
> chore: remove peer deps

- README.md
- package.json
- src/index.js
- test/index.spec.js
Depends on:
BREAKING CHANGE: uses the CID class from the new multiformats module
> chore: update to new multiformats

- package.json
[Apparently](https://github.com/libp2p/js-libp2p-delegated-content-routing/blob/master/src/index.js#L4), `peer-id` is required for normal operations. Move it from `devDependencies` to `dependencies` section.
> chore: Make peer-id a normal dependency

- README.md
- package.json
- src/index.ts
- test/index.spec.ts
`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection
> fix!: remove @libp2p/components

- package.json
- test/index.spec.ts
related https://github.com/libp2p/js-libp2p/issues/1681
> refactor: remove use of timeout-abort-controller
